name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      MOCKPASS_PORT: 5156
      SHOW_LOGIN_PAGE: true
      MOCKPASS_NRIC: S8979373D
      SIGN_ASSERTION: false
      ENCRYPT_ASSERTION: false
      SIGN_RESPONSE: false
      RESOLVE_ARTIFACT_REQUEST_SIGNED: false
      ENCRYPT_MYINFO: false
      SERVICE_PROVIDER_MYINFO_SECRET: ${{ secrets.SERVICE_PROVIDER_MYINFO_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: npm ci
      - run: npm install
      - run: npx lockfile-lint --type npm --path package-lock.json --validate-https --allowed-hosts npm
      - run: npm run lint
